# Generated by Django 5.2.6 on 2025-09-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0004_contactquery_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tdl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tdls/')),
            ],
        ),
    ]
